### ISSUE TITLE
Questions about predefined anchor centers.

### ISSUE THREAD

**Issue by missyoudaisy** [geyanqi/SAR#4]
Hello, in your paper, there exist three kinds of predefined anchors, namely, standard normal distributions, random orthogonal matrix and random matrix with a maximum equiangular separability structure.  However, I only find one implementation for standard normal distributions in sar.py, 
`self.register_buffer('random_center', torch.randn(self.class_numbers, self.feat_channel))`

Where can i find the implementation of the other two methods?

**Comment by geyanqi** [comment]
For a random orthogonal matrix, you can directly initialize a zero tensor with dimensions (N, C), where N is the number of classes and C is the <input_channels> of the classifier. Then randomly insert a 1 into each C-dimensional tensor, but ensure that the two are orthogonal.

For a maximum equiangular separability structure, please refer to this [paper](https://arxiv.org/abs/2301.01100)

**Comment by missyoudaisy** [comment]
thanks for your reply  :)

**Comment by missyoudaisy** [comment]
> For a random orthogonal matrix, you can directly initialize a zero tensor with dimensions (N, C), where N is the number of classes and C is the <input_channels> of the classifier. Then randomly insert a 1 into each C-dimensional tensor, but ensure that the two are orthogonal.
> 
> For a maximum equiangular separability structure, please refer to this [paper](https://arxiv.org/abs/2301.01100)

Sorry，i didn't find the code of paper "Understanding Imbalanced Semantic Segmentation Through Neural Collapse", how did you realize the maximum equiangular separability structure and which code did you reference? Could you please tell me? thank you ~ @geyanqi
